"""Initial migration

Revision ID: ecd4e4edbf5d
Revises:
Create Date: 2025-04-09 14:26:15.567318

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecd4e4edbf5d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("lat", sa.DECIMAL(precision=8, scale=4), nullable=False),
        sa.Column("lon", sa.DECIMAL(precision=8, scale=4), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_forecast",
        sa.Column("dt", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("temp", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("feels_like", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("pressure", sa.Integer(), nullable=True),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.Column("wind_speed", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("dt"),
    )
    op.create_table(
        "weather_conditions",
        sa.Column("dt", sa.BigInteger(), nullable=False),
        sa.Column("main_condition", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("clouds", sa.Integer(), nullable=True),
        sa.Column("pop", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.Column("rain_3h", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("snow_3h", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["dt"],
            ["weather_forecast.dt"],
        ),
        sa.PrimaryKeyConstraint("dt"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_conditions")
    op.drop_table("weather_forecast")
    op.drop_table("city")
    # ### end Alembic commands ###
